# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e8dfa504e57b7c42110d26df5e90348ae71c51ff3e7252e1a65954377d72956d175685fa4c03258ef96c1bdfa833e428d1b0ebb2031c96a34bf80575b1dd31e4

test:
  secret_key_base: 2be286079f1f399132d1464d8c0d705a8882b789997d38ae1c4fbe4360ac09a3d9a6178ca83e0224e1e2f47fcea11fdba7765c8c553adf293ed8fabb50dc9a80

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
