# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 41c1b206820520eccd4ed7cdff6dca61f1922365f55552368525bf6b32264dfb27778b88d4cc7f0da7879b0c5c9f3e0f759f7ba55dffd85a5e2e4ae84e2bbfa4
  facebook_app_id: 176711186401841
  facebook_app_secret: 46b41e89d1242c9a3fb5e96f072b4284
  server_url: http://localhost:3001
  git_client_id: 7d1d2a52f780c9df4e1e
  git_client_secret: 8ac07f2b185fdeb757307983aab075b697d5a2a7

test:
  secret_key_base: 9ea237ddfc936f1e9d7dd1ddee09b10479db45fa6bd6e958bfbac62c6f1dbc1d9923da00aca460fe2cea1acd4afdc86c61d1e49a8799d8d0d6bf87282575cd14

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  server_url: http://earth-broken.bnr.la
  git_client_id: fd5cd10d8bdff392350b
  git_client_secret: 0ff201111e7c9a47ec675aec8d9c3595344ff632

